### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by triplethreat1469** [NebulaMods/OVH-API#2]
no issue just saying hi

**Comment by linklel11** [comment]
Hi
`wait() game.workspace:clear() loop until nil`

**Comment by natedamack304** [comment]
Yooooooo wass good cuties 😘

**Comment by natedamack304** [comment]
Stop muting me Barry your literally named after a fruit and look like one too.

**Comment by triplethreat1469** [comment]
dont unmute nate thats mad funny

**Comment by xenos1337** [comment]
@everyone !!!! 100% worked

**Comment by xenos1337** [comment]
I just got the phone app to ask for unmute bbg 😍🥰

**Comment by xenos1337** [comment]
Yes m

**Comment by xenos1337** [comment]
https://youtu.be/PXqcHi2fkXI

**Comment by xenos1337** [comment]
close this ssue man

**Comment by xenos1337** [comment]
😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢😭⭐😎😊😂🤣❤️😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️✌️🤞😉🎶😢
